### PR TITLE
Add Tianyi to author list.

### PR DESCRIPTION
**Pull request by tianyizhangcs**

### CODE REVIEW

**Comment by hkaiser** [comment]
@tianyi93 would you like to add you paper(s) in the text?

**Comment by tianyizhangcs** [comment]
@hkaiser Sure, which part should I add them to? 
Should I just add them under "HPX is utilized in a diverse set of applications: "?

**Comment by tianyizhangcs** [comment]
@hkaiser  Done, let me know if any updates are needed :)

**Review by hkaiser — APPROVED** [review]
Thanks!

**Pull request merged**
